development:
  adapter: postgresql
  database: zi_data_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: zi_data_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: zi_data_production
  pool: 5
  timeout: 5000